[package]
name = "winwalk"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["fileapi", "handleapi", "timezoneapi"] }
bitflags = "2.4.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "walk"
harness = false
